lines:
- id: 1
  points:
  - - 627
    - 352
  - - 851
    - 357
- id: 2
  points:
  - - 825
    - 404
  - - 506
    - 395
- id: 3
  points:
  - - 723
    - 630
  - - 37
    - 584
method: linear
roi:
- - 697
  - 707
- - 2
  - 599
- - 569
  - 368
- - 673
  - 333
- - 857
  - 336
- - 694
  - 710
